name: Deploy React to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent and Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu

            # Clone repo if it doesn't exist
            if [ ! -d "ec2_react" ]; then
              git clone https://github.com/ekrambd/ec2_react.git
            fi

            cd ec2_react

            git pull origin master

            npm install

            # Start or restart app with PM2
            if pm2 list | grep -q "react-app"; then
              echo "PM2 process exists. Restarting..."
              pm2 restart react-app
            else
              echo "PM2 process does not exist. Starting..."
              pm2 start "npm run dev -- --host 0.0.0.0" --name react-app
            fi
          EOF
